---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: centos-6.5
  run_list:
  - recipe[yum-epel]

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[haproxy_test]
  attributes: {}
- name: feature-haproxy-dev
  run_list:
  - recipe[haproxy_test]
  attributes: {
    "haproxy": {
      "use_dev": true
    }
  }
